### PR TITLE
Static analysis tests

### PR DESCRIPTION
**Pull request by darthorimar**
Reproduced evaluation from paper `Demand-Driven Alias Analysis for C`
*  on a few-line C code
*  on 12k sloc gzip

### CODE REVIEW

**Comment by gsvgit** [comment]
Cool! What about performance of alias analysis on real graphs?

**Comment by darthorimar** [comment]
For gzip it takes about 1.5s on neo4j graph

**Comment by gsvgit** [comment]
Is this graph one of used for evaluation in "Efficient Subcubic Alias Analysis for C"? Is it possible to compare performance of our implementation with results from the paper?

**Comment by darthorimar** [comment]
This is a graph generated by the same tool they used to generate PEGs for their paper. This tool also contains alias analysis algorithm they implemented for this paper. So, it is possible to compare results on the same data :)

**Comment by darthorimar** [comment]
Oh, and I pointed out to the wrong article. The right one is `Demand-Driven Alias Analysis for C`. The test programs from a first one is too large

**Comment by gsvgit** [comment]
Too large for our tool or for publishing on GitHub?

Great! So we can use it for our tools evaluation.

**Comment by darthorimar** [comment]
Too large for meerkat, I think. They use for evaluation Linux kernel, Wine and other large stuff

**Pull request merged**
