### PR TITLE
SPPF lazy trees

### PR DESCRIPTION
**Pull request by ilya-nozhkin**

### CODE REVIEW

**Comment by gsvgit** [comment]
Cool!

**Comment by gsvgit** [comment]
@ilya-nozhkin Please, add tests for next cases:
1) Input is a graph, output SPPF contains a finite number of trees
2) Input is a graph, output SPPF contains an infinite number of trees. For example.
Grammar: S -> a S b | a b
Graph:  0 -a->1 ; 1 -a->2; 2 -a->0; 0-b->3; 3 -b-> 0;
3) Input is a graph, output SPPF contains an infinite number of trees, grammar contains action (demantic) code. (example of semantic actoins can be found here^ https://github.com/meerkat-parser/papers/blob/master/pepm16.pdf | Figure 1).  For example try to specify semantic actions for AST construction for previous example.

**Comment by ilya-nozhkin** [comment]
Cases 1 and 2 are already added (see the first two tests for graph input)

**Comment by gsvgit** [comment]
Ou.. Ok. Please, add the example from case 2. It is a classic example.

**Pull request merged**
